### ISSUE TITLE
Progress bar in table not centered on mobile

### ISSUE THREAD

**Issue by mgd722** [vikdiesel/admin-one-vue-bulma-dashboard#1]
Awesome dashboard! By the time you read this I'll have already bought my copy, but I figured I'd point it out anyway:

![image](https://user-images.githubusercontent.com/12187845/62830020-4a893180-bbc4-11e9-9482-0396bfd818a1.png)

Problem manifests on my iPhone X in both Safari and Chrome, and on my MacBook Pro when the screen width is small.

**Comment by vikdiesel** [comment]
Hi Mike,

Thank you for buying Admin One! Issue is now fixed. You're free to re-download dashboard files via Gumroad.

`Updated: /src/scss/_table.scss (lines 92-97)`

<pre>
span, progress {
  display: flex;
  width: 45%;
  align-items: center;
  align-self: center;
}
</pre>
