### ISSUE TITLE
Icons seem out of alignment?

### ISSUE THREAD

**Issue by mgd722** [vikdiesel/admin-one-vue-bulma-dashboard#2]
[This gif probably displays it best.](http://www.giphy.com/gifs/QsyY2uymXSBVYp7yin) Toggling between the free version and the paid version, it becomes apparent that the icons/text seem to not line up? It happens anywhere that there are icons, regardless of text, but in the AsideMenu it seems that the text is also vertically off center.

Not lining up on paid version:
![image](https://user-images.githubusercontent.com/12187845/62874378-5a953400-bcde-11e9-8219-6299aeb53ffe.png)

Lining up on free version:
![image](https://user-images.githubusercontent.com/12187845/62874446-7ac4f300-bcde-11e9-94ad-d99712961117.png)

Been loving it so far! Very nice and clean.

**Comment by mgd722** [comment]
Also, hah, looking at it now it doesn't seem like a big difference but it was one of the first things my designer sister noticed.

**Comment by mgd722** [comment]
The plot thickens...I just hard reloaded the free site, and now both are out of alignment. I'm guessing I had an older version cached and maybe the icons not lining up is a recent thing?

**Comment by vikdiesel** [comment]
Hi, thank you for pointing out. Yesterday I've updated buefy to 0.8.x branch, so, probably, that's what caused an issue.

Committed `src/scss/_icon-fix.scss`

Preview: https://admin-one-free.justboil.me/ (hard reload required)
