### ISSUE TITLE
Collapsible Menu

### ISSUE THREAD

**Issue by mronoffon** [vikdiesel/admin-one-vue-bulma-dashboard#3]
Hi..
Does the free version come with a collapsible menu?  What else is missing from the free version?

Thanks

**Comment by vikdiesel** [comment]
Hi @mronoffon 

Premium version has a more advanced menu, updates widget (on the right), login screen, password reset screen, error screen, lock screen and some more stuff. The best way is to compare visually:

- Premium version https://admin-one-vue-cli.justboil.me
- Free version https://admin-one-free.justboil.me
